### ISSUE TITLE
成员无法右键告示牌运行指令

### ISSUE THREAD

**Issue by fgr178707** [wifi-left/sign-editor#1]
服务器成员右键告示牌没有反应

命令如下:

`/give @s minecraft:bread{display:{Name:'{"text":"\\u00A7b新手面包"}',Lore:['{"text":"\\u00A74\\u00A7c请不要将此面包丢给村民"}','{"text":"\\u00A74\\u00A7c请不要将此面包丢给村民"}']}} 64`

**Comment by wifi-left** [comment]
按理说应该只是命令错了

**Comment by wifi-left** [comment]
你是服务器吗？把出生点保护关掉试试

**Comment by wifi-left** [comment]
本地试了下，没有任何问题。

还有，服务器安装本模组没有，没安装了话服务器上的修改是无法生效的。

当然如果你在本地修改完了再上传地图到服务器，服务器就不需要这个模组了

**Comment by wifi-left** [comment]
如果还是不行，请运行命令：`/data get block <方块坐标>` 并把结果发出来，比如这样：
![image](https://github.com/wifi-left/sign-editor/assets/63381531/e45cab74-d613-4a03-b579-01f94126cf3f)

**Comment by fgr178707** [comment]
> 你是服务器吗？把出生点保护关掉试试

好的 我等服务器开了我试试

**Comment by fgr178707** [comment]
> 你是服务器吗？把出生点保护关掉试试

我的问题 领地保护忘关了 已解决
